// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/r/:roomId": {
    params: {
      "roomId": string;
    };
  };
  "/zrocket": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/r/:roomId" | "/zrocket";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "routes/room/index.tsx": {
    id: "routes/room/index";
    page: "/r/:roomId";
  };
  "routes/zrocket.tsx": {
    id: "routes/zrocket";
    page: "/zrocket";
  };
};