// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/d": {
    params: {};
  };
  "/d/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/p": {
    params: {};
  };
  "/p/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/c": {
    params: {};
  };
  "/c/:channelId": {
    params: {
      "channelId": string;
    };
  };
  "/files": {
    params: {};
  };
  "/preferences": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/demos/rich-message-editor": {
    params: {};
  };
  "/demos/copy-paste": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/d" | "/d/:chatId" | "/p" | "/p/:chatId" | "/c" | "/c/:channelId" | "/files" | "/preferences" | "/support" | "/demos/rich-message-editor" | "/demos/copy-paste";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "components/layout/index.tsx": {
    id: "components/layout/index";
    page: "/d" | "/d/:chatId" | "/p" | "/p/:chatId" | "/c" | "/c/:channelId";
  };
  "routes/direct/layout.tsx": {
    id: "routes/direct/layout";
    page: "/d" | "/d/:chatId";
  };
  "routes/direct/index.tsx": {
    id: "routes/direct/index";
    page: "/d";
  };
  "routes/direct/chat.tsx": {
    id: "routes/direct/chat";
    page: "/d/:chatId";
  };
  "routes/groups/layout.tsx": {
    id: "routes/groups/layout";
    page: "/p" | "/p/:chatId";
  };
  "routes/groups/index.tsx": {
    id: "routes/groups/index";
    page: "/p";
  };
  "routes/groups/chat.tsx": {
    id: "routes/groups/chat";
    page: "/p/:chatId";
  };
  "routes/channels/layout.tsx": {
    id: "routes/channels/layout";
    page: "/c" | "/c/:channelId";
  };
  "routes/channels/index.tsx": {
    id: "routes/channels/index";
    page: "/c";
  };
  "routes/channels/channel.tsx": {
    id: "routes/channels/channel";
    page: "/c/:channelId";
  };
  "routes/files/index.tsx": {
    id: "routes/files/index";
    page: "/files";
  };
  "routes/preferences/index.tsx": {
    id: "routes/preferences/index";
    page: "/preferences";
  };
  "routes/support/index.tsx": {
    id: "routes/support/index";
    page: "/support";
  };
  "routes/demos/rich-editor-demo.tsx": {
    id: "routes/demos/rich-editor-demo";
    page: "/demos/rich-message-editor";
  };
  "routes/demos/copy-paste-demo.tsx": {
    id: "routes/demos/copy-paste-demo";
    page: "/demos/copy-paste";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "components/layout/index": typeof import("./app/components/layout/index.tsx");
  "routes/direct/layout": typeof import("./app/routes/direct/layout.tsx");
  "routes/direct/index": typeof import("./app/routes/direct/index.tsx");
  "routes/direct/chat": typeof import("./app/routes/direct/chat.tsx");
  "routes/groups/layout": typeof import("./app/routes/groups/layout.tsx");
  "routes/groups/index": typeof import("./app/routes/groups/index.tsx");
  "routes/groups/chat": typeof import("./app/routes/groups/chat.tsx");
  "routes/channels/layout": typeof import("./app/routes/channels/layout.tsx");
  "routes/channels/index": typeof import("./app/routes/channels/index.tsx");
  "routes/channels/channel": typeof import("./app/routes/channels/channel.tsx");
  "routes/files/index": typeof import("./app/routes/files/index.tsx");
  "routes/preferences/index": typeof import("./app/routes/preferences/index.tsx");
  "routes/support/index": typeof import("./app/routes/support/index.tsx");
  "routes/demos/rich-editor-demo": typeof import("./app/routes/demos/rich-editor-demo.tsx");
  "routes/demos/copy-paste-demo": typeof import("./app/routes/demos/copy-paste-demo.tsx");
};