// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/d": {
    params: {};
  };
  "/d/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/p": {
    params: {};
  };
  "/p/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/c": {
    params: {};
  };
  "/c/:channelId": {
    params: {
      "channelId": string;
    };
  };
  "/preferences": {
    params: {};
  };
  "/files": {
    params: {};
  };
  "/help-support": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/info": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/d" | "/d/:chatId" | "/p" | "/p/:chatId" | "/c" | "/c/:channelId" | "/preferences" | "/files" | "/help-support" | "/messages" | "/info";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "routes/d/layout.tsx": {
    id: "routes/d/layout";
    page: "/d" | "/d/:chatId";
  };
  "routes/d/index.tsx": {
    id: "routes/d/index";
    page: "/d";
  };
  "routes/d/chat.tsx": {
    id: "routes/d/chat";
    page: "/d/:chatId";
  };
  "routes/private-groups/layout.tsx": {
    id: "routes/private-groups/layout";
    page: "/p" | "/p/:chatId";
  };
  "routes/private-groups/index.tsx": {
    id: "routes/private-groups/index";
    page: "/p";
  };
  "routes/private-groups/chat.tsx": {
    id: "routes/private-groups/chat";
    page: "/p/:chatId";
  };
  "routes/c/layout.tsx": {
    id: "routes/c/layout";
    page: "/c" | "/c/:channelId";
  };
  "routes/c/index.tsx": {
    id: "routes/c/index";
    page: "/c";
  };
  "routes/c/channel.tsx": {
    id: "routes/c/channel";
    page: "/c/:channelId";
  };
  "pages/UserPreferencesPage.tsx": {
    id: "pages/UserPreferencesPage";
    page: "/preferences";
  };
  "pages/FilesPage.tsx": {
    id: "pages/FilesPage";
    page: "/files";
  };
  "pages/HelpSupportPage.tsx": {
    id: "pages/HelpSupportPage";
    page: "/help-support";
  };
  "routes/messages/index.tsx": {
    id: "routes/messages/index";
    page: "/messages";
  };
  "routes/zrocket.tsx": {
    id: "routes/zrocket";
    page: "/info";
  };
};