packages:
  - libs/*
  - apps/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@rocicorp/zero-sqlite3'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs

shamefullyHoist: true
