packages:
  - libs/*
  - apps/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@rocicorp/zero'
  - '@rocicorp/zero-sqlite3'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - unrs-resolver

overrides:
  source-map: ^0.7.6

shamefullyHoist: true
