# auth config for zero-cache
auth:
  # an auth token zero-cache should send in the `k` query string parameter to authenticate
  token: 65cad6a9c688c04c7d2b28c3f98bf9c0d602a240e3b9f232600f0065bfabba15

# config for the upstream MongoDB database
db:
  # The URL of the MongoDB database
  # uri: mongodb://127.0.0.1:27017/pg-sync-test
  # uri: mongodb://localhost:27017/pg-sync-test
  uri: mongodb://localhost:27017/zstart

  db: zstart

  # A list of collections to publish changes from
  publish:
    # - pokemon
    # - issue
    - medium
    - user
    - message
# 
# TODO: consider allowing the use of a unique aggregation pipeline per collection
# 
#   # A list of collections to publish changes from
#   publish:
#     - collection: test
#       pipeline:
#         - $match:
#             operationType: insert
#         - $project: 
#             _id: 1
#             name: 1
#             age: 1
#             password: 0

# config for the NATS KV server
kv:
  # the list of NATS servers to connect to, specify multiple servers for HA
  servers:
    - nats://localhost:34222
  
  # NATS auth credentials
  auth:
    # NATS user. Must be specified together with `pwd`
    user: zero
    
    # NATS pwd. Must be specified together with `user`
    pwd: zero
