export const USER_PRESENCE_ONLINE = 'ONLINE';
export const USER_PRESENCE_AWAY = 'AWAY';
export const USER_PRESENCE_OFFLINE = 'OFFLINE';
export const USER_PRESENCE_BUSY = 'BUSY';
export const USER_PRESENCE_DISABLED = 'DISABLED';

export const USER_PRESENCE_STATUSES = [
    USER_PRESENCE_ONLINE,
    USER_PRESENCE_AWAY,
    USER_PRESENCE_OFFLINE,
    USER_PRESENCE_BUSY,
    USER_PRESENCE_DISABLED
] as const;

export type UserPresenceStatus = (typeof USER_PRESENCE_STATUSES)[number];
