import { loader } from 'fumadocs-core/source';
// import { icons } from 'lucide-react';
// import { createElement } from 'react';

import { docs, create } from '@/source';

/**
 * Create source from docs configuration
 * Uses docs.doc and docs.meta generated by fumadocs-mdx vite plugin
 *
 * This is a .server.ts file, so it only runs on the server and can use top-level await
 */
export const source = loader({
    source: await create.sourceAsync(docs.doc, docs.meta),
    baseUrl: '/docs',
    icon(icon) {
        // Return the icon name as a string - the sidebar component will resolve it
        // This allows RR7 to serialize the icon name in the page tree
        return icon;
    }
});

export const { getPage, getPages, pageTree } = source;
