# auth config
auth:
  # settings for the built-in JWT auth provider
  jwt:
    # secret used to sign JWTs
    secret: 65cad6a9c688c04c7d2b28c3f98bf9c0d602a240e3b9f232600f0065bfabba15

    # duration in seconds that tokens signed by teh built-in auth provider
    # are valid for
    tokenLifetime: 6000

  # GitHub OAuth app settings
  github:
    # GitHub app client ID
    clientId: Iv23liuWwyhqHfyTw2AJ

    # GitHub app client secret
    clientSecret: 0e6f0ce84e0a4e0b7f88adaece92f760f3809518

    # GitHub Authorization Code grant callback URL
    callbackUrl: http://localhost:8011/auth/github/callback

# config for the upstream MongoDB database
db:
  # The URL of the MongoDB database that will store the shard metadata. May be
  # the same as the database holding your app data.
  uri: mongodb://localhost:27017/zchat

# zero-cache change source settings
zero:
  # auth config for zero-cache
  auth:
    # an auth token zero-cache should send in the `k` query string parameter to
    # authenticate. Make this whatever you want, but keep it secret. You'll need
    # to include this in the URL you give zero-cache in the `ZERO_UPSTREAM_DB` env
    # variable.
    token: 65cad6a9c688c04c7d2b28c3f98bf9c0d602a240e3b9f232600f0065bfabba15

  # config for the KV service that stores mappings between Change Stream resume
  # tokens and Zero replication watermarks
  kv:
    # specify `zqlite` to use a @rocicorp/zero-sqlite3 backed KV store
    provider: zqlite

    # config for the zqlite KV store provider
    zqlite:
      # The path to the SQLite database file
      file: ./kv.sqlite
