name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # this makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build libraries
        run: pnpm build:libs

      - name: Run tests
        run: pnpm test

      - name: Run lint
        run: pnpm lint

      - name: Check for changeset
        run: |
          if [ "${{ github.event.pull_request.user.login }}" = "dependabot[bot]" ]; then
            echo "Skipping changeset check for dependabot"
            exit 0
          fi
          
          if ! pnpm changeset status --since=origin/main 2>&1 | grep -q "No changesets found"; then
            echo "✅ Changeset found"
            exit 0
          else
            echo "❌ No changeset found. Please run 'pnpm changeset' to add one."
            echo ""
            echo "If your changes don't require a version bump (e.g., documentation updates, internal refactoring),"
            echo "you can add an empty changeset by running:"
            echo "  pnpm changeset add --empty"
            exit 1
          fi
